// Using packages in your module by passing it as an argument to the require function.
const inquirer = require("inquirer");
const readMeGenerate = require("./utils/readMeGenerator")
const fileSystem = require("fs"); 

// Questions object that will be  generated by the README file
const questions = [
     
    {
      type: "input",
      message: "What is the title for your project?",
      name: "Title",
    },
    {
      type: "input",
      message: "Tell us a little bit about your project:",
      name: "Description",
    },
    {
      type: "input",
      message: "What are the steps to successfully run this application?",
      name: "Installation",
    },
    {
      type: "input",
      message: "Who  would you recommend to use this project:",
      name: "Usage",
    },
    {
      type: "list",
      message: "Please choose a licence you have used for this project?",
      name: "License",
      choices: ['ISC License', 'MIT License', 'Apache 2.0 Licence, Version 2.0', 'BSD-2-Clause', 'None of the above']
    },
    {
      type: "input",
      message: "Please provide your contributions for this project:",
      name: "Contribution",
    },
    {
      type: "input",
      message: "What type of testing have you done for this project?:",
      name: "Test",
    },
    {
      type: "input",
      message: "In order for users to contact you, what is your email address?",
      name: "Email",
    },
    {
        type: "input",
        message: "In order for users to acces your code, what is your GitHub username?",
        name: "githubAccount",
      },
  ];
  

// The write to the README file
function writeToREADME(fileName, data) {

fileSystem.writeFile("./"+fileName, data, function(err) {
  //If an error is thrown it it caught up  here
  if (err) {
    return console.log(err);
  }
  console.log ("Your new README file is as follows: " + fileName);
});

}

// Function to initialise questions asked
function init() {
  inquirer.prompt(questions)
  .then(function(data) {
    writeToREADME("README.md", readMeGenerate(data));
  });
}


// Executing the application
init();